export const meals = [
  {
    id: 1,
    mealName: "High-Protein Oatmeal",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 320,
    mealProtein: 25,
    mealCarbs: 40,
    mealFats: 5,
    mealIngridients: [
      {
        ingridient: "Oats",
        grams: 20,
      },
      {
        ingridient: "Whey Protein",
        grams: 30,
      },
      {
        ingridient: "Almond milk",
        grams: 200,
      },
      {
        ingridient: "Blueberries",
        grams: 100,
      },
    ],
  },
  {
    id: 2,
    mealName: "Scrambled Eggs & Avocado Toast",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 350,
    mealProtein: 20,
    mealCarbs: 15,
    mealFats: 22,
    mealIngridients: [
      {
        ingridient: "Eggs",
        grams: 150,
      },
      {
        ingridient: "Bread 1 slice",
        grams: 40,
      },
      {
        ingridient: "Avocado",
        grams: 50,
      },
    ],
  },
  {
    id: 3,
    mealName: "Cottage Cheese & Pineapple Bowl",
    mealTag: "Breakfast",
    mealPrepTime: "3min",
    mealCalories: 230,
    mealProtein: 24,
    mealCarbs: 20,
    mealFats: 3,
    mealIngridients: [
      {
        ingridient: "Cottage cheese (low-fat)",
        grams: 200,
      },
      {
        ingridient: "Pineapple chunks",
        grams: 100,
      }
    ],
  },
  {
    id: 4,
    mealName: "Spinach & Feta Egg White Omelette",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 180,
    mealProtein: 25,
    mealCarbs: 2,
    mealFats: 6,
    mealIngridients: [
      {
        ingridient: "Egg whites",
        grams: 200,
      },
      {
        ingridient: "Spinach",
        grams: 50,
      },
      {
        ingridient: "Feta cheese",
        grams: 30,
      },
    ],
  },
  {
    id: 5,
    mealName: "Peanut Butter & Banana Smoothie",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 290,
    mealProtein: 27,
    mealCarbs: 35,
    mealFats: 7,
    mealIngridients: [
      {
        ingridient: "Banana",
        grams: 100,
      },
      {
        ingridient: "Peanut butter",
        grams: 10,
      },
      {
        ingridient: "Almond milk",
        grams: 200,
      },
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 6,
    mealName: "Smoked Salmon on Rye Bread",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 200,
    mealProtein: 16,
    mealCarbs: 12,
    mealFats: 7,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 7,
    mealName: "Protein Pancakes",
    mealTag: "Breakfast",
    mealPrepTime: "15min",
    mealCalories: 280,
    mealProtein: 30,
    mealCarbs: 25,
    mealFats: 4,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 8,
    mealName: "Greek Yogurt Parfait",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 210,
    mealProtein: 15,
    mealCarbs: 25,
    mealFats: 4,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 9,
    mealName: "Turkey & Egg Breakfast Wrap",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 290,
    mealProtein: 22,
    mealCarbs: 20,
    mealFats: 10,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 10,
    mealName: "Avocado & Egg Bowl",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 250,
    mealProtein: 15,
    mealCarbs: 5,
    mealFats: 18,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 11,
    mealName: "Apple & Almond Butter Toast",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 200,
    mealProtein: 5,
    mealCarbs: 28,
    mealFats: 7,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 12,
    mealName: "Chia Pudding",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 210,
    mealProtein: 10,
    mealCarbs: 12,
    mealFats: 12,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 13,
    mealName: "Protein French Toast",
    mealTag: "Breakfast",
    mealPrepTime: "15min",
    mealCalories: 350,
    mealProtein: 30,
    mealCarbs: 35,
    mealFats: 10,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 14,
    mealName: "Tuna & Avocado Crackers",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 220,
    mealProtein: 18,
    mealCarbs: 18,
    mealFats: 7,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 15,
    mealName: "High-Protein Smoothie Bowl",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 480,
    mealProtein: 33,
    mealCarbs: 62,
    mealFats: 14,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 16,
    mealName: "Egg & Spinach Breakfast Muffins",
    mealTag: "Breakfast",
    mealPrepTime: "20min",
    mealCalories: 230,
    mealProtein: 28,
    mealCarbs: 2,
    mealFats: 12,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 17,
    mealName: "Protein Overnight Oats",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 300,
    mealProtein: 25,
    mealCarbs: 35,
    mealFats: 5,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 18,
    mealName: "Turkey Bacon & Egg Sandwich",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 250,
    mealProtein: 18,
    mealCarbs: 20,
    mealFats: 8,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 19,
    mealName: "Tofu Scramble & Veggies",
    mealTag: "Breakfast",
    mealPrepTime: "15min",
    mealCalories: 180,
    mealProtein: 20,
    mealCarbs: 8,
    mealFats: 8,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 20,
    mealName: "Berry Protein Waffles",
    mealTag: "Breakfast",
    mealPrepTime: "15min",
    mealCalories: 300,
    mealProtein: 28,
    mealCarbs: 35,
    mealFats: 5,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 21,
    mealName: "Grilled Chicken Salad",
    mealTag: "Lunch",
    mealPrepTime: "15min",
    mealCalories: 280,
    mealProtein: 35,
    mealCarbs: 5,
    mealFats: 10,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 22,
    mealName: "Quinoa & Salmon Bowl",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 400,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 15,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 23,
    mealName: "Turkey & Sweet Potato",
    mealTag: "Lunch",
    mealPrepTime: "25min",
    mealCalories: 350,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 8,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 24,
    mealName: "Tuna Salad Wrap",
    mealTag: "Lunch",
    mealPrepTime: "10min",
    mealCalories: 280,
    mealProtein: 35,
    mealCarbs: 20,
    mealFats: 7,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 25,
    mealName: "Chicken & Brown Rice Bowl",
    mealTag: "Lunch",
    mealPrepTime: "25min",
    mealCalories: 360,
    mealProtein: 35,
    mealCarbs: 35,
    mealFats: 7,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 26,
    mealName: "Turkey Burger Bowl",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 330,
    mealProtein: 30,
    mealCarbs: 10,
    mealFats: 20,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 27,
    mealName: "Grilled Shrimp & Couscous",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 320,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 5,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 28,
    mealName: "Teriyaki Chicken Bowl",
    mealTag: "Lunch",
    mealPrepTime: "25min",
    mealCalories: 380,
    mealProtein: 35,
    mealCarbs: 40,
    mealFats: 5,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 29,
    mealName: "Spicy Chicken & Veggie Stir-Fry",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 350,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 7,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 30,
    mealName: "Turkey Meatball Zoodles",
    mealTag: "Lunch",
    mealPrepTime: "30min",
    mealCalories: 250,
    mealProtein: 35,
    mealCarbs: 10,
    mealFats: 8,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 31,
    mealName: "Lentil & Chicken Soup",
    mealTag: "Lunch",
    mealPrepTime: "30min",
    mealCalories: 290,
    mealProtein: 30,
    mealCarbs: 30,
    mealFats: 8,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 32,
    mealName: "Beef & Quinoa Bowl",
    mealTag: "Lunch",
    mealPrepTime: "25min",
    mealCalories: 450,
    mealProtein: 33,
    mealCarbs: 35,
    mealFats: 21,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 33,
    mealName: "Salmon & Asparagus Plate",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 400,
    mealProtein: 35,
    mealCarbs: 25,
    mealFats: 15,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 34,
    mealName: "Grilled Chicken & Hummus Wrap",
    mealTag: "Lunch",
    mealPrepTime: "10min",
    mealCalories: 320,
    mealProtein: 30,
    mealCarbs: 25,
    mealFats: 9,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 35,
    mealName: "Cod & Vegetable Bowl",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 330,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 5,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 36,
    mealName: "Baked Chicken Thighs & Rice",
    mealTag: "Lunch",
    mealPrepTime: "40min",
    mealCalories: 400,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 12,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 37,
    mealName: "Vegan Tofu & Quinoa Bowl",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 320,
    mealProtein: 30,
    mealCarbs: 25,
    mealFats: 8,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 38,
    mealName: "Grilled Steak & Sweet Potato",
    mealTag: "Lunch",
    mealPrepTime: "30min",
    mealCalories: 380,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 10,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 39,
    mealName: "Black Bean & Chicken Burrito",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 320,
    mealProtein: 30,
    mealCarbs: 35,
    mealFats: 6,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
  {
    id: 40,
    mealName: "Turkey & Rice Stuffed Peppers",
    mealTag: "Lunch",
    mealPrepTime: "40min",
    mealCalories: 300,
    mealProtein: 35,
    mealCarbs: 25,
    mealFats: 6,
    mealIngridients: [
      {
        ingridient: "Whey protein",
        grams: 30,
      },
    ],
  },
];
