export const meals = [
  {
    mealName: "High-Protein Oatmeal",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 320,
    mealProtein: 25,
    mealCarbs: 40,
    mealFats: 5,
  },
  {
    mealName: "Scrambled Eggs & Avocado Toast",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 350,
    mealProtein: 20,
    mealCarbs: 15,
    mealFats: 22,
  },
  {
    mealName: "Cottage Cheese & Pineapple Bowl",
    mealTag: "Breakfast",
    mealPrepTime: "3min",
    mealCalories: 230,
    mealProtein: 24,
    mealCarbs: 20,
    mealFats: 3,
  },
  {
    mealName: "Spinach & Feta Egg White Omelette",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 180,
    mealProtein: 25,
    mealCarbs: 2,
    mealFats: 6,
  },
  {
    mealName: "Peanut Butter & Banana Smoothie",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 290,
    mealProtein: 27,
    mealCarbs: 35,
    mealFats: 7,
  },
  {
    mealName: "Smoked Salmon on Rye Bread",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 200,
    mealProtein: 16,
    mealCarbs: 12,
    mealFats: 7,
  },
  {
    mealName: "Protein Pancakes",
    mealTag: "Breakfast",
    mealPrepTime: "15min",
    mealCalories: 280,
    mealProtein: 30,
    mealCarbs: 25,
    mealFats: 4,
  },
  {
    mealName: "Greek Yogurt Parfait",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 210,
    mealProtein: 15,
    mealCarbs: 25,
    mealFats: 4,
  },
  {
    mealName: "Turkey & Egg Breakfast Wrap",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 290,
    mealProtein: 22,
    mealCarbs: 20,
    mealFats: 10,
  },
  {
    mealName: "Avocado & Egg Bowl",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 250,
    mealProtein: 15,
    mealCarbs: 5,
    mealFats: 18,
  },
  {
    mealName: "Apple & Almond Butter Toast",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 200,
    mealProtein: 5,
    mealCarbs: 28,
    mealFats: 7,
  },
  {
    mealName: "Chia Pudding",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 210,
    mealProtein: 10,
    mealCarbs: 12,
    mealFats: 12,
  },
  {
    mealName: "Protein French Toast",
    mealTag: "Breakfast",
    mealPrepTime: "15min",
    mealCalories: 350,
    mealProtein: 30,
    mealCarbs: 35,
    mealFats: 10,
  },
  {
    mealName: "Tuna & Avocado Crackers",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 220,
    mealProtein: 18,
    mealCarbs: 18,
    mealFats: 7,
  },
  {
    mealName: "High-Protein Smoothie Bowl",
    mealTag: "Breakfast",
    mealPrepTime: "5min",
    mealCalories: 480,
    mealProtein: 33,
    mealCarbs: 62,
    mealFats: 14,
  },
  {
    mealName: "Egg & Spinach Breakfast Muffins",
    mealTag: "Breakfast",
    mealPrepTime: "20min",
    mealCalories: 230,
    mealProtein: 28,
    mealCarbs: 2,
    mealFats: 12,
  },
  {
    mealName: "Protein Overnight Oats",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 300,
    mealProtein: 25,
    mealCarbs: 35,
    mealFats: 5,
  },
  {
    mealName: "Turkey Bacon & Egg Sandwich",
    mealTag: "Breakfast",
    mealPrepTime: "10min",
    mealCalories: 250,
    mealProtein: 18,
    mealCarbs: 20,
    mealFats: 8,
  },
  {
    mealName: "Tofu Scramble & Veggies",
    mealTag: "Breakfast",
    mealPrepTime: "15min",
    mealCalories: 180,
    mealProtein: 20,
    mealCarbs: 8,
    mealFats: 8,
  },
  {
    mealName: "Berry Protein Waffles",
    mealTag: "Breakfast",
    mealPrepTime: "15min",
    mealCalories: 300,
    mealProtein: 28,
    mealCarbs: 35,
    mealFats: 5,
  },
  {
    mealName: "Grilled Chicken Salad",
    mealTag: "Lunch",
    mealPrepTime: "15min",
    mealCalories: 280,
    mealProtein: 35,
    mealCarbs: 5,
    mealFats: 10,
  },
  {
    mealName: "Quinoa & Salmon Bowl",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 400,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 15,
  },
  {
    mealName: "Turkey & Sweet Potato",
    mealTag: "Lunch",
    mealPrepTime: "25min",
    mealCalories: 350,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 8,
  },
  {
    mealName: "Tuna Salad Wrap",
    mealTag: "Lunch",
    mealPrepTime: "10min",
    mealCalories: 280,
    mealProtein: 35,
    mealCarbs: 20,
    mealFats: 7,
  },
  {
    mealName: "Chicken & Brown Rice Bowl",
    mealTag: "Lunch",
    mealPrepTime: "25min",
    mealCalories: 360,
    mealProtein: 35,
    mealCarbs: 35,
    mealFats: 7,
  },
  {
    mealName: "Turkey Burger Bowl",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 330,
    mealProtein: 30,
    mealCarbs: 10,
    mealFats: 20,
  },
  {
    mealName: "Grilled Shrimp & Couscous",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 320,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 5,
  },
  {
    mealName: "Teriyaki Chicken Bowl",
    mealTag: "Lunch",
    mealPrepTime: "25min",
    mealCalories: 380,
    mealProtein: 35,
    mealCarbs: 40,
    mealFats: 5,
  },
  {
    mealName: "Spicy Chicken & Veggie Stir-Fry",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 350,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 7,
  },
  {
    mealName: "Turkey Meatball Zoodles",
    mealTag: "Lunch",
    mealPrepTime: "30min",
    mealCalories: 250,
    mealProtein: 35,
    mealCarbs: 10,
    mealFats: 8,
  },
  {
    mealName: "Lentil & Chicken Soup",
    mealTag: "Lunch",
    mealPrepTime: "30min",
    mealCalories: 290,
    mealProtein: 30,
    mealCarbs: 30,
    mealFats: 8,
  },
  {
    mealName: "Beef & Quinoa Bowl",
    mealTag: "Lunch",
    mealPrepTime: "25min",
    mealCalories: 450,
    mealProtein: 33,
    mealCarbs: 35,
    mealFats: 21,
  },
  {
    mealName: "Salmon & Asparagus Plate",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 400,
    mealProtein: 35,
    mealCarbs: 25,
    mealFats: 15,
  },
  {
    mealName: "Grilled Chicken & Hummus Wrap",
    mealTag: "Lunch",
    mealPrepTime: "10min",
    mealCalories: 320,
    mealProtein: 30,
    mealCarbs: 25,
    mealFats: 9,
  },
  {
    mealName: "Cod & Vegetable Bowl",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 330,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 5,
  },
  {
    mealName: "Baked Chicken Thighs & Rice",
    mealTag: "Lunch",
    mealPrepTime: "40min",
    mealCalories: 400,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 12,
  },
  {
    mealName: "Vegan Tofu & Quinoa Bowl",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 320,
    mealProtein: 30,
    mealCarbs: 25,
    mealFats: 8,
  },
  {
    mealName: "Grilled Steak & Sweet Potato",
    mealTag: "Lunch",
    mealPrepTime: "30min",
    mealCalories: 380,
    mealProtein: 35,
    mealCarbs: 30,
    mealFats: 10,
  },
  {
    mealName: "Black Bean & Chicken Burrito",
    mealTag: "Lunch",
    mealPrepTime: "20min",
    mealCalories: 320,
    mealProtein: 30,
    mealCarbs: 35,
    mealFats: 6,
  },
  {
    mealName: "Turkey & Rice Stuffed Peppers",
    mealTag: "Lunch",
    mealPrepTime: "40min",
    mealCalories: 300,
    mealProtein: 35,
    mealCarbs: 25,
    mealFats: 6,
  },
];
